{% set name = "git-story" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/git-story-{{ version }}.tar.gz
  sha256: d5b0f45dca0646c8104ede268efd0ee75ba3f13838bf4e024cd629b0e44206e0

build:
  entry_points:
    - git-story=git_story.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - gitpython
    - manim

test:
  imports:
    - git_story
  commands:
    - pip check
    - git-story --help
  requires:
    - pip
    - git

about:
  home: https://initialcommit.com/tools/git-story
  summary: Tell the story of your Git project by creating video animations (.mp4) of your commit history directly from your Git repo.
  license: 'MIT'
  license_file: license

extra:
  recipe-maintainers:
    - marcelotrevisani
